### PR TITLE
additional voltmeter data sheet for reference

### PR DESCRIPTION
**Pull request by KrishUCI**

### CODE REVIEW

**Comment by Roman-Parise** [comment]
It looks like you did your part of the introduction section. Instead of putting it in the Sample.tex file, can you put it in a new *.tex file with some title like intro_voltmeter.tex or something like that?

You also need to do your portion of the implementation section in the email.

A brief explanation or derivation (very brief) of the voltage division equation would also be nice. Just enough to demonstrate that it makes sense. Like a sentence description of how to derive or reference the two or so relationships required to derive it. You should also make it clearer why the voltmeter circuit follows a voltage division rule.

**Comment by KrishUCI** [comment]
Oh ya my bad dude i didnt finish the report yet. I dont know why it got on
git hub

**Comment by Roman-Parise** [comment]
Yeah. Make a pull request at the end of the lab, though we may want that datasheet. Not sure how to go about doing that

**Comment by Roman-Parise** [comment]
1) Make sure before you do this, you've pushed your changes to your fork. Pull the upstream repo: git pull https://github.com/Roman-Parise/Circuits-Lab.git . I made some changes to things like .gitignore and other parts of the repo.
2) Cite the datasheets to which you are referring for the specs (https://www.imperial.ac.uk/media/imperial-college/administration-and-support-services/library/public/LaTeX-and-BibTeX-branded-jan-2016.pdf)
3) Use \pm and not +/-.
4) Put a picture of the voltmeter circuit with component values (very important that component values be included) in the document. Reference that figure and explain that it is a voltage divider circuit and thus follows that equation. If you take the picture from a lab manual or some other source, please cite it. (https://www.sharelatex.com/learn/Referencing_Figures)
5) If you have an equation eqn formatted like $eqn$, format it instead like this:
\begin{equation}
\label{eq:volt_div}
eqn
\end{equation}
Change the label (e.g. volt_div) depending on the equation. Give it a good name. Reference it, I think using something like \ref{eq:volt_div} but don't quote me on that one. This ensures all equations are numbered. You may need to compile LaTeX twice (just press the green arrow twice) for reasons I'll explain later (if I understand them myself).
6) All sentences should be third person present tense.
7) Make sure you use the omega symbol whenever referencing resistor units and not just k or M.
8) Don't say that a formula for the DVM's impedance will be derived. It's your job to derive it. Derive it from your voltage division equation and indirectly reference it in the text like in 5.
9) manufacturer's not manufacturers for possessives
10) We aren't measuring impedance for the oscilloscope. We're measuring V_scope/V_AC. Refer to that equation as "equation \ref{eq:osc_ratio}" in the text. Jason should be deriving that, so email/text Jason and tell him to label that equation as eq:osc_ratio in his section.

**Comment by KrishUCI** [comment]
Ok so a couple of things. I keep getting error for the +/- if i do \pm. So if you can do me a favor and just add it in that would be great. Second thing is I can't find a picture of the circuit with added resistor values. If you have a picture available either put it in or send it to me and I'll insert it. I have the normal picture of the circuit up. Everything else I believe is good to go.

**Comment by Roman-Parise** [comment]
Alright, I can handle the +/- issue. I also don't have a pic on me. Build the circuit in pspice and the values should be controllable there. Then just use snipping tool to take a pic. The process takes maybe about 10 minutes or so. Jason did the same thing, so it'll look consistent.

**Comment by Roman-Parise** [comment]
Also, if you haven't already done the citations, I mentioned I would do them in my email last week. So, I can cite if you need me to. Just let me know what manuals you used.

**Pull request merged**
