### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by jhw305**

### CODE REVIEW

**Comment by Roman-Parise** [comment]
Alright, I'll review this pull request tomorrow before compiling the final doc. Just make sure you pulled the upstream repo and tidy up your repo before I do: git pull https://github.com/Roman-Parise/Circuits-Lab.git .

**Comment by jhw305** [comment]
It should be ready to go. Let me know if you need me to change anything.

**Comment by jhw305** [comment]
Also, I included the amsmath package to help format some of my calculations. Include it in the final copy if you haven't already. Thanks!

**Comment by Roman-Parise** [comment]
Looks good. I can handle the citation of the lab manual since I said I would. Just one thing before accepting the pull request: do we need to include more explanation in DVM Results.tex? Maybe I just put way too much in my section.

**Pull request merged**
